### ISSUE TITLE
Not Showing Trades From Additional Additions

### ISSUE THREAD

**Issue by TeaCows** [GrigLog/RoughlyEnoughTrades#1]
Not showing trades from (https://www.curseforge.com/minecraft/mc-mods/additional-additions)

**Comment by GrigLog** [comment]
1.18 or 1.19?

**Comment by GrigLog** [comment]
This happens because Additional Additions abuses mixins to override the refresh behaviour (https://github.com/Additional-Mods/additionaladditions/blob/main/src/main/java/dqu/additionaladditions/mixin/WanderingTraderMixin.java) instead of adding their trade into the game list. There is no way for me to track down the code changes, the incompability is on their side
